version: 1.5.{build}
image: Visual Studio 2019
configuration: ReleaseCI
init:
  - git config --global core.autocrlf false
branches:
  only:
    - master
skip_tags:  true
only_commits:
  files:
    - Visualizer.Shared
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- cmd: nuget restore

matrix:
  fast_finish: true

artifacts:
  - path: ExpressionTreeVisualizer.2019\bin\ReleaseCI\ExpressionTreeVisualizer.2019.dll
    type: File
    name: visualizer

  - path: ExpressionTreeVisualizer.2019\bin\ReleaseCI\*.pdb
    type: File
    name: visualizer

  - path: ExpressionTreeVisualizer.2019\bin\ReleaseCI\MultiSelectTreeView.dll
    type: File
    name: visualizer

deploy:
  - provider: GitHub
    desciprion: ''
    auth_token:
      secure: aJaTRXIa+zc+SOGdNPKTH+znUun60Jh5b5pdjzLslhnoKk4vh1eoqO/vnGcDEwig
    artifact: visualizer